In [1]:
import re
import pandas as pd
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt

In [50]:
with open("../data/raw/all_genres_chart_source.html", "r", encoding="utf-8") as f:
    html = f.read()

print(html[:500])

<!doctype html>
<head>

	<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-TV9F68FR5Y" type="eabc8260c164f3f2546fd7d9-text/javascript"></script>
<script type="eabc8260c164f3f2546fd7d9-text/javascript">
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-TV9F68FR5Y');
</script>




<meta charset="UTF-8">
<meta name="DESCRIPTION" content="Rankings for Artists, Trac

In [51]:
soup = BeautifulSoup(html, "lxml")

print("TITLE:", soup.title.text if soup.title else "No title found")

rows = soup.find_all("div", id="top10artistchart-full")
print("Main chart rows found:", len(rows))

TITLE: BeatStats - Top Tracks
Main chart rows found: 100

In [52]:
print(rows[0].prettify()[:2500])

<div id="top10artistchart-full">
 <div id="top10artistchart-number">
  1
 </div>
 <div id="top10artistchart-image">
  <img height="50" src="/images/track/small/20625808.jpg?version=27739"/>
 </div>
 <div id="top10trackchart-text-large">
  <div id="top10trackchart-artistname">
   JONAS BLUE, MALIVE
  </div>
  <div id="top10trackchart-title">
   <strong>
    Edge of Desire
   </strong>
  </div>
  <div id="top10trackchart-points">
   <strong>
    21094
   </strong>
   POINTS /
   <strong>
    285
   </strong>
   DAYS
   <div id="genreplacement">
    <span class="curved-box" style="background-color: #8d4654;">
     HOUSE
    </span>
   </div>
  </div>
  <a href="https://www.beatport.com/track/edge-of-desire/20625808" target="_blank">
   <div id="shopping-icon-full">
    <img height="20" src="/_images/interface/shopping_icon_alpha.png" width="20"/>
   </div>
  </a>
  <a data-cf-modified-eabc8260c164f3f2546fd7d9-="" href="#" id="20625808" onclick="if (!window.__cfRLUnblockHandlers) return false; audioplayerget(this.id);return false;">
   <div id="play-icon-full">
    <img height="22" src="/_images/interface/play_icon_alpha.png" width="22"/>
   </div>
  </a>
 </div>
</div>

In [53]:
def parse_points_days(text):
    points_match = re.search(r"(\d+)\s+POINTS", text)
    days_match = re.search(r"(\d+)\s+DAYS", text)

    points = int(points_match.group(1)) if points_match else None
    days = int(days_match.group(1)) if days_match else None

    return points, days

In [54]:
def parse_artists(artist_text):
    if not artist_text:
        return []
    return [a.strip() for a in artist_text.split(",") if a.strip()]

In [55]:
def parse_genre_from_row(row):
    genre_div = row.find("div", id="genreplacement")
    if genre_div:
        genre_text = genre_div.get_text(" ", strip=True)
        if genre_text:
            return genre_text

    for tag in row.find_all(["div", "span"]):
        tag_id = (tag.get("id") or "").lower()
        tag_classes = " ".join(tag.get("class", [])).lower()
        text = tag.get_text(" ", strip=True)

        if ("genre" in tag_id or "genre" in tag_classes) and text:
            return text

    return ""

In [56]:
chart_data = []

for row in rows:
    rank_tag = row.find("div", id="top10artistchart-number")
    artist_tag = row.find("div", id="top10trackchart-artistname")
    title_tag = row.find("div", id="top10trackchart-title")
    points_tag = row.find("div", id="top10trackchart-points")

    # Rank + rise amount
    rank_text = rank_tag.get_text(" ", strip=True) if rank_tag else ""
    numbers = re.findall(r"\d+", rank_text)

    rank = int(numbers[0]) if len(numbers) >= 1 else None
    rise_amount = int(numbers[1]) if len(numbers) >= 2 else 0

    # Other fields
    artist_text = artist_tag.get_text(strip=True) if artist_tag else ""
    title = title_tag.get_text(strip=True) if title_tag else ""
    points_text = points_tag.get_text(" ", strip=True) if points_tag else ""

    points, days = parse_points_days(points_text)
    artists = parse_artists(artist_text)
    genre = parse_genre_from_row(row)

    beatport_link = ""
    for a in row.find_all("a", href=True):
        href = a["href"]
        if "beatport.com/track/" in href:
            beatport_link = href
            break

    chart_data.append({
        "rank": rank,
        "rise_amount": rise_amount,
        "is_rising": rise_amount > 0,
        "artist_raw": artist_text,
        "artists": artists,
        "num_artists": len(artists),
        "title": title,
        "genre": genre,
        "points": points,
        "days": days,
        "beatport_link": beatport_link
    })

len(chart_data), chart_data[:10]

(100,
 [{'rank': 1,
   'rise_amount': 0,
   'is_rising': False,
   'artist_raw': 'JONAS BLUE, MALIVE',
   'artists': ['JONAS BLUE', 'MALIVE'],
   'num_artists': 2,
   'title': 'Edge of Desire',
   'genre': 'HOUSE',
   'points': 21094,
   'days': 285,
   'beatport_link': 'https://www.beatport.com/track/edge-of-desire/20625808'},
  {'rank': 2,
   'rise_amount': 0,
   'is_rising': False,
   'artist_raw': 'TINASHE, DISCO LINES',
   'artists': ['TINASHE', 'DISCO LINES'],
   'num_artists': 2,
   'title': 'No Broke Boys',
   'genre': 'DANCE / POP',
   'points': 17922,
   'days': 258,
   'beatport_link': 'https://www.beatport.com/track/no-broke-boys/20601832'},
  {'rank': 3,
   'rise_amount': 0,
   'is_rising': False,
   'artist_raw': 'MAU P',
   'artists': ['MAU P'],
   'num_artists': 1,
   'title': 'Like I Like It',
   'genre': 'TECH HOUSE',
   'points': 16951,
   'days': 251,
   'beatport_link': 'https://www.beatport.com/track/like-i-like-it/20505201'},
  {'rank': 4,
   'rise_amount': 0,
   'is_rising': False,
   'artist_raw': 'HUGEL, SOLTO (FR)',
   'artists': ['HUGEL', 'SOLTO (FR)'],
   'num_artists': 2,
   'title': 'Jamaican (Bam Bam)',
   'genre': 'AFRO HOUSE',
   'points': 16248,
   'days': 173,
   'beatport_link': 'https://www.beatport.com/track/jamaican-bam-bam/22357262'},
  {'rank': 5,
   'rise_amount': 3,
   'is_rising': True,
   'artist_raw': 'JAMBACK',
   'artists': ['JAMBACK'],
   'num_artists': 1,
   'title': 'Positive',
   'genre': 'MINIMAL / DEEP TECH',
   'points': 15176,
   'days': 173,
   'beatport_link': 'https://www.beatport.com/track/positive/22236272'},
  {'rank': 6,
   'rise_amount': 0,
   'is_rising': False,
   'artist_raw': 'TOMAN',
   'artists': ['TOMAN'],
   'num_artists': 1,
   'title': 'Verano En NY',
   'genre': 'TECH HOUSE',
   'points': 13549,
   'days': 228,
   'beatport_link': 'https://www.beatport.com/track/verano-en-ny/20564331'},
  {'rank': 7,
   'rise_amount': 0,
   'is_rising': False,
   'artist_raw': 'CID, TAYLR RENEE',
   'artists': ['CID', 'TAYLR RENEE'],
   'num_artists': 2,
   'title': 'Fancy $hit',
   'genre': 'TECH HOUSE',
   'points': 13304,
   'days': 170,
   'beatport_link': 'https://www.beatport.com/track/fancy-hit/21309496'},
  {'rank': 8,
   'rise_amount': 0,
   'is_rising': False,
   'artist_raw': 'PROSPA',
   'artists': ['PROSPA'],
   'num_artists': 1,
   'title': "Don't Stop",
   'genre': 'TECH HOUSE',
   'points': 12579,
   'days': 237,
   'beatport_link': 'https://www.beatport.com/track/dont-stop/20311844'},
  {'rank': 9,
   'rise_amount': 0,
   'is_rising': False,
   'artist_raw': 'PROSPA, KOSMO KINT',
   'artists': ['PROSPA', 'KOSMO KINT'],
   'num_artists': 2,
   'title': 'Love Songs (feat. Kosmo Kint)',
   'genre': 'HOUSE',
   'points': 12178,
   'days': 174,
   'beatport_link': 'https://www.beatport.com/track/love-songs-feat-kosmo-kint/21977538'},
  {'rank': 10,
   'rise_amount': 1,
   'is_rising': True,
   'artist_raw': 'DA HOOL, CASSIAN, YOTTO',
   'artists': ['DA HOOL', 'CASSIAN', 'YOTTO'],
   'num_artists': 3,
   'title': 'Love Parade',
   'genre': 'MELODIC HOUSE & TECHNO',
   'points': 11337,
   'days': 154,
   'beatport_link': 'https://www.beatport.com/track/love-parade/21774346'}])

In [57]:
df = pd.DataFrame(chart_data)
df = df.drop_duplicates(subset=["rank", "artist_raw", "title"])
df = df.sort_values("rank").reset_index(drop=True)

df.head(10)

,rank,rise_amount,is_rising,artist_raw,artists,num_artists,title,genre,points,days,beatport_link
0,1,0,False,"JONAS BLUE, MALIVE","[JONAS BLUE, MALIVE]",2,Edge of Desire,HOUSE,21094,285,https://www.beatport.com/track/edge-of-desire/...
1,2,0,False,"TINASHE, DISCO LINES","[TINASHE, DISCO LINES]",2,No Broke Boys,DANCE / POP,17922,258,https://www.beatport.com/track/no-broke-boys/2...
2,3,0,False,MAU P,[MAU P],1,Like I Like It,TECH HOUSE,16951,251,https://www.beatport.com/track/like-i-like-it/...
3,4,0,False,"HUGEL, SOLTO (FR)","[HUGEL, SOLTO (FR)]",2,Jamaican (Bam Bam),AFRO HOUSE,16248,173,https://www.beatport.com/track/jamaican-bam-ba...
4,5,3,True,JAMBACK,[JAMBACK],1,Positive,MINIMAL / DEEP TECH,15176,173,https://www.beatport.com/track/positive/22236272
5,6,0,False,TOMAN,[TOMAN],1,Verano En NY,TECH HOUSE,13549,228,https://www.beatport.com/track/verano-en-ny/20...
6,7,0,False,"CID, TAYLR RENEE","[CID, TAYLR RENEE]",2,Fancy $hit,TECH HOUSE,13304,170,https://www.beatport.com/track/fancy-hit/21309496
7,8,0,False,PROSPA,[PROSPA],1,Don't Stop,TECH HOUSE,12579,237,https://www.beatport.com/track/dont-stop/20311844
8,9,0,False,"PROSPA, KOSMO KINT","[PROSPA, KOSMO KINT]",2,Love Songs (feat. Kosmo Kint),HOUSE,12178,174,https://www.beatport.com/track/love-songs-feat...
9,10,1,True,"DA HOOL, CASSIAN, YOTTO","[DA HOOL, CASSIAN, YOTTO]",3,Love Parade,MELODIC HOUSE & TECHNO,11337,154,https://www.beatport.com/track/love-parade/217...

In [58]:
df["rise_str"] = df["rise_amount"].apply(lambda x: f"+{x}" if x > 0 else "0")

df[["rank", "rise_amount", "rise_str", "is_rising", "artist_raw", "title", "genre"]].head(20)

,rank,rise_amount,rise_str,is_rising,artist_raw,title,genre
0,1,0,0,False,"JONAS BLUE, MALIVE",Edge of Desire,HOUSE
1,2,0,0,False,"TINASHE, DISCO LINES",No Broke Boys,DANCE / POP
2,3,0,0,False,MAU P,Like I Like It,TECH HOUSE
3,4,0,0,False,"HUGEL, SOLTO (FR)",Jamaican (Bam Bam),AFRO HOUSE
4,5,3,+3,True,JAMBACK,Positive,MINIMAL / DEEP TECH
5,6,0,0,False,TOMAN,Verano En NY,TECH HOUSE
6,7,0,0,False,"CID, TAYLR RENEE",Fancy $hit,TECH HOUSE
7,8,0,0,False,PROSPA,Don't Stop,TECH HOUSE
8,9,0,0,False,"PROSPA, KOSMO KINT",Love Songs (feat. Kosmo Kint),HOUSE
9,10,1,+1,True,"DA HOOL, CASSIAN, YOTTO",Love Parade,MELODIC HOUSE & TECHNO
10,11,1,+1,True,SIDEPIECE,Cry For You,DANCE / POP
11,12,9,+9,True,"ULTRA NATE, HUGEL",Free (You Got To Live),AFRO HOUSE
12,13,1,+1,True,BABES ON THE RUN,Power,FUNKY HOUSE
13,14,1,+1,True,"CHRIS LAKE, THE CHEMICAL BROTHERS",Galvanize,DANCE / POP
14,15,1,+1,True,CHRIS LORENZO,Appetite,TECH HOUSE
15,16,2,+2,True,"MAX DEAN, LUKE DEAN, LOCKY (UK)",Can't Decide,DEEP HOUSE
16,17,3,+3,True,"CALVIN HARRIS, CLEMENTINE DOUGLAS",Blessings,DANCE / POP
17,18,4,+4,True,"AUDIO BULLYS, CHRIS LORENZO, MAX STYLER",London's On Fire,TECH HOUSE
18,19,5,+5,True,"KATE LINN, PROVI, FANTOMEL",Dame Un Grrr (Provi Remix),AFRO HOUSE
19,20,5,+5,True,FALLON (IE),Diet Coke,TECH HOUSE

In [59]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

df

,rank,rise_amount,is_rising,artist_raw,artists,num_artists,title,genre,points,days,beatport_link,rise_str
0,1,0,False,"JONAS BLUE, MALIVE","[JONAS BLUE, MALIVE]",2,Edge of Desire,HOUSE,21094,285,https://www.beatport.com/track/edge-of-desire/...,0
1,2,0,False,"TINASHE, DISCO LINES","[TINASHE, DISCO LINES]",2,No Broke Boys,DANCE / POP,17922,258,https://www.beatport.com/track/no-broke-boys/2...,0
2,3,0,False,MAU P,[MAU P],1,Like I Like It,TECH HOUSE,16951,251,https://www.beatport.com/track/like-i-like-it/...,0
3,4,0,False,"HUGEL, SOLTO (FR)","[HUGEL, SOLTO (FR)]",2,Jamaican (Bam Bam),AFRO HOUSE,16248,173,https://www.beatport.com/track/jamaican-bam-ba...,0
4,5,3,True,JAMBACK,[JAMBACK],1,Positive,MINIMAL / DEEP TECH,15176,173,https://www.beatport.com/track/positive/22236272,+3
5,6,0,False,TOMAN,[TOMAN],1,Verano En NY,TECH HOUSE,13549,228,https://www.beatport.com/track/verano-en-ny/20...,0
6,7,0,False,"CID, TAYLR RENEE","[CID, TAYLR RENEE]",2,Fancy $hit,TECH HOUSE,13304,170,https://www.beatport.com/track/fancy-hit/21309496,0
7,8,0,False,PROSPA,[PROSPA],1,Don't Stop,TECH HOUSE,12579,237,https://www.beatport.com/track/dont-stop/20311844,0
8,9,0,False,"PROSPA, KOSMO KINT","[PROSPA, KOSMO KINT]",2,Love Songs (feat. Kosmo Kint),HOUSE,12178,174,https://www.beatport.com/track/love-songs-feat...,0
9,10,1,True,"DA HOOL, CASSIAN, YOTTO","[DA HOOL, CASSIAN, YOTTO]",3,Love Parade,MELODIC HOUSE & TECHNO,11337,154,https://www.beatport.com/track/love-parade/217...,+1
10,11,1,True,SIDEPIECE,[SIDEPIECE],1,Cry For You,DANCE / POP,11170,156,https://www.beatport.com/track/cry-for-you/215...,+1
11,12,9,True,"ULTRA NATE, HUGEL","[ULTRA NATE, HUGEL]",2,Free (You Got To Live),AFRO HOUSE,10713,151,https://www.beatport.com/track/free-you-got-to...,+9
12,13,1,True,BABES ON THE RUN,[BABES ON THE RUN],1,Power,FUNKY HOUSE,10626,224,https://www.beatport.com/track/power/20692753,+1
13,14,1,True,"CHRIS LAKE, THE CHEMICAL BROTHERS","[CHRIS LAKE, THE CHEMICAL BROTHERS]",2,Galvanize,DANCE / POP,10594,146,https://www.beatport.com/track/galvanize/21200241,+1
14,15,1,True,CHRIS LORENZO,[CHRIS LORENZO],1,Appetite,TECH HOUSE,10406,162,https://www.beatport.com/track/appetite/20450483,+1
15,16,2,True,"MAX DEAN, LUKE DEAN, LOCKY (UK)","[MAX DEAN, LUKE DEAN, LOCKY (UK)]",3,Can't Decide,DEEP HOUSE,9683,189,https://www.beatport.com/track/cant-decide/205...,+2
16,17,3,True,"CALVIN HARRIS, CLEMENTINE DOUGLAS","[CALVIN HARRIS, CLEMENTINE DOUGLAS]",2,Blessings,DANCE / POP,9601,132,https://www.beatport.com/track/blessings/20462394,+3
17,18,4,True,"AUDIO BULLYS, CHRIS LORENZO, MAX STYLER","[AUDIO BULLYS, CHRIS LORENZO, MAX STYLER]",3,London's On Fire,TECH HOUSE,9283,154,https://www.beatport.com/track/londons-on-fire...,+4
18,19,5,True,"KATE LINN, PROVI, FANTOMEL","[KATE LINN, PROVI, FANTOMEL]",3,Dame Un Grrr (Provi Remix),AFRO HOUSE,9148,146,https://www.beatport.com/track/dame-un-grrr-pr...,+5
19,20,5,True,FALLON (IE),[FALLON (IE)],1,Diet Coke,TECH HOUSE,8996,117,https://www.beatport.com/track/diet-coke/22095452,+5
20,21,22,True,BRUNELLO,[BRUNELLO],1,Ghost Dance,INDIE DANCE,8836,121,https://www.beatport.com/track/ghost-dance/231...,+22
21,22,5,True,"VANCO, AYA.SYSTEM","[VANCO, AYA.SYSTEM]",2,Ma Tnsani (Yalla Habibi) (feat. AYA.SYSTEM),AFRO HOUSE,8792,149,https://www.beatport.com/track/ma-tnsani-yalla...,+5
22,23,0,False,"CHRIS LAKE, RAGIE BAN","[CHRIS LAKE, RAGIE BAN]",2,Toxic,TECH HOUSE,8520,138,https://www.beatport.com/track/toxic/20291674,0
23,24,8,True,SUPERNOVA,[SUPERNOVA],1,Velvet Avenue,HOUSE,8452,134,https://www.beatport.com/track/velvet-avenue/2...,+8
24,25,3,True,VINTER (BR),[VINTER (BR)],1,Space Pump,HOUSE,8297,124,https://www.beatport.com/track/space-pump/2102...,+3
25,26,3,True,"EMPIRE OF THE SUN, BLOND:ISH","[EMPIRE OF THE SUN, BLOND:ISH]",2,Walking On A Dream,DANCE / POP,8211,133,https://www.beatport.com/track/walking-on-a-dr...,+3
26,27,0,False,"JOCELYN BROWN, LUKE ALESSI, CHLOé CAILLET","[JOCELYN BROWN, LUKE ALESSI, CHLOé CAILLET]",3,The One,HOUSE,8097,125,https://www.beatport.com/track/the-one/20307568,0
27,28,0,False,MAU P,[MAU P],1,The Less I Know The Better,TECH HOUSE,7838,139,https://www.beatport.com/track/the-less-i-know...,0
28,29,2,True,FEZZO,[FEZZO],1,Kids,DANCE / POP,7786,84,https://www.beatport.com/track/kids/22448219,+2
29,30,3,True,"KURD MAVERICK, HUGEL","[KURD MAVERICK, HUGEL]",2,PYHU (Put Your Hands Up),AFRO HOUSE,7590,119,https://www.beatport.com/track/pyhu-put-your-h...,+3
30,31,3,True,"SHAKEDOWN, LAYTON GIORDANI, ANYMA (OFC)","[SHAKEDOWN, LAYTON GIORDANI, ANYMA (OFC)]",3,At Night (Anyma x Layton Giordani Extended Remix),MELODIC HOUSE & TECHNO,7542,123,https://www.beatport.com/track/at-night/20661162,+3
31,32,3,True,JULIAN FIJMA,[JULIAN FIJMA],1,Get Stupid,MINIMAL / DEEP TECH,7539,124,https://www.beatport.com/track/get-stupid/2088...,+3
32,33,3,True,"BOBBY SHMURDA, SIDEPIECE","[BOBBY SHMURDA, SIDEPIECE]",2,Cash Out,TECH HOUSE,7506,134,https://www.beatport.com/track/cash-out/20566956,+3
33,34,0,False,RÜFÜS DU SOL,[RÜFÜS DU SOL],1,In the Moment (Adriatique Extended Remix),MELODIC HOUSE & TECHNO,7498,155,https://www.beatport.com/track/in-the-moment/2...,0
34,35,2,True,"MODJO, SPARROW & BARBOSSA, KOSHI, DAYMAAN, SPA...","[MODJO, SPARROW & BARBOSSA, KOSHI, DAYMAAN, SP...",5,Lady (Hear Me Tonight) - Remix,AFRO HOUSE,7469,120,https://www.beatport.com/track/lady-hear-me-to...,+2
35,36,42,True,MAU P,[MAU P],1,neck,TECH HOUSE,7340,82,https://www.beatport.com/track/neck/23308330,+42
36,37,48,True,TRACE (UZ),[TRACE (UZ)],1,Good Time,HOUSE,7337,81,https://www.beatport.com/track/good-time/23443670,+48
37,38,0,False,BISCITS,[BISCITS],1,Crush,TECH HOUSE,7210,107,https://www.beatport.com/track/crush/20362602,0
38,39,0,False,"NATE DOGG, KOLTER","[NATE DOGG, KOLTER]",2,Liquor Store,HOUSE,6986,92,https://www.beatport.com/track/liquor-store/20...,0
39,40,0,False,"CAMELPHAT, ELDERBROOK, ARTBAT","[CAMELPHAT, ELDERBROOK, ARTBAT]",3,Cola,TECH HOUSE,6957,98,https://www.beatport.com/track/cola/20790162,0
40,41,0,False,BONAFIQUE,[BONAFIQUE],1,Monologue,INDIE DANCE,6953,154,https://www.beatport.com/track/monologue/20962298,0
41,42,6,True,"NICK CURLY, JOëLLA JACKSON","[NICK CURLY, JOëLLA JACKSON]",2,Attention,DEEP HOUSE,6937,138,https://www.beatport.com/track/attention/22480525,+6
42,43,36,True,ESSE (US),[ESSE (US)],1,Make My Day,TECH HOUSE,6857,84,https://www.beatport.com/track/make-my-day/234...,+36
43,44,0,False,"VINTAGE CULTURE, GABSS","[VINTAGE CULTURE, GABSS]",2,Lost,MELODIC HOUSE & TECHNO,6804,76,https://www.beatport.com/track/lost/22738898,0
44,45,0,False,"EMANUELE ESPOSITO, GIANNI ROMANO, HELEN TESFAZ...","[EMANUELE ESPOSITO, GIANNI ROMANO, HELEN TESFA...",4,It's Not Right,AFRO HOUSE,6753,126,https://www.beatport.com/track/its-not-right/2...,0
45,46,0,False,SAMM (BE),[SAMM (BE)],1,Body Language,HOUSE,6636,90,https://www.beatport.com/track/body-language/2...,0
46,47,34,True,JOSHWA,[JOSHWA],1,Out of My Mind,TECH HOUSE,6466,82,https://www.beatport.com/track/out-of-my-mind/...,+34
47,48,51,True,"REINIER ZONNEVELD, GORDO","[REINIER ZONNEVELD, GORDO]",2,Loco Loco,DANCE / POP,6448,75,https://www.beatport.com/track/loco-loco/23904036,+51
48,49,0,False,"ADAM PORT, STRYV, MALACHIII","[ADAM PORT, STRYV, MALACHIII]",3,Positions,AFRO HOUSE,6424,91,https://www.beatport.com/track/positions/20674436,0
49,50,0,False,SCRIPT,[SCRIPT],1,WTF,TECH HOUSE,6324,106,https://www.beatport.com/track/wtf/20796447,0
50,51,0,False,"MK, CHRYSTAL","[MK, CHRYSTAL]",2,Dior,HOUSE,6297,95,https://www.beatport.com/track/dior/20528357,0
51,52,0,False,MESTO,[MESTO],1,Caramelle,MAINSTAGE,6272,85,https://www.beatport.com/track/caramelle/22741059,0
52,53,0,False,"MARSHALL JEFFERSON, MAESIC, SALOMé DAS","[MARSHALL JEFFERSON, MAESIC, SALOMé DAS]",3,Life Is Simple (Move Your Body),AFRO HOUSE,6219,100,https://www.beatport.com/track/life-is-simple-...,0
53,54,0,False,"MR. BELT & WEZOL, RUZE","[MR. BELT & WEZOL, RUZE]",2,Ain't Nobody,HOUSE,6183,92,https://www.beatport.com/track/aint-nobody/213...,0
54,55,0,False,DISCIP,[DISCIP],1,Pull Up,TECH HOUSE,6110,80,https://www.beatport.com/track/pull-up/22866908,0
55,56,0,False,L.P. RHYTHM,[L.P. RHYTHM],1,Versatile,HOUSE,6022,89,https://www.beatport.com/track/versatile/20719741,0
56,57,0,False,"TIESTO, ODD MOB, GOODBOYS","[TIESTO, ODD MOB, GOODBOYS]",3,Won't Be Possible,DANCE / POP,5971,91,https://www.beatport.com/track/wont-be-possibl...,0
57,58,0,False,"THREE DRIVES, THREE DRIVES ON A VINYL, MAX STYLER","[THREE DRIVES, THREE DRIVES ON A VINYL, MAX ST...",3,Greece 2000,TRANCE (MAIN FLOOR),5772,80,https://www.beatport.com/track/greece-2000/230...,0
58,59,1,True,ALAIA & GALLO,[ALAIA & GALLO],1,Lipstick,TECH HOUSE,5696,114,https://www.beatport.com/track/lipstick/20572171,+1
59,60,1,True,"ODD MOB, OMNOM, HYPERBEAM","[ODD MOB, OMNOM, HYPERBEAM]",3,Coming Up (It's Dare),DANCE / POP,5682,84,https://www.beatport.com/track/coming-up-its-d...,+1
60,61,1,True,MPH,[MPH],1,Raw,UK GARAGE / BASSLINE,5645,130,https://www.beatport.com/track/raw/20533994,+1
61,62,1,True,"CALVIN HARRIS, D.O.D","[CALVIN HARRIS, D.O.D]",2,Sweet Nothing,DANCE / POP,5635,86,https://www.beatport.com/track/sweet-nothing/2...,+1
62,63,1,True,"HECTOR COUTO, ALEJANDRO PAZ","[HECTOR COUTO, ALEJANDRO PAZ]",2,El House,HOUSE,5486,89,https://www.beatport.com/track/el-house/20431852,+1
63,64,1,True,EMANUEL SATIE,[EMANUEL SATIE],1,Give It All,HOUSE,5473,85,https://www.beatport.com/track/give-it-all/223...,+1
64,65,2,True,"ODD MOB, OMNOM, HYPERBEAM","[ODD MOB, OMNOM, HYPERBEAM]",3,System,TECH HOUSE,5387,78,https://www.beatport.com/track/system/21251156,+2
65,66,2,True,"MOBY, BLOND:ISH, KIKO FRANCO","[MOBY, BLOND:ISH, KIKO FRANCO]",3,Natural Blues,HOUSE,5359,73,https://www.beatport.com/track/natural-blues/2...,+2
66,67,155,True,"ANOTR, 54 ULTRA","[ANOTR, 54 ULTRA]",2,Talk To You,HOUSE,5345,54,https://www.beatport.com/track/talk-to-you/245...,+155
67,68,1,True,"SONNY FODERA, D.O.D, POPPY BASKCOMB","[SONNY FODERA, D.O.D, POPPY BASKCOMB]",3,Think About Us,DANCE / POP,5322,119,https://www.beatport.com/track/think-about-us/...,+1
68,69,1,True,TINI GESSLER,[TINI GESSLER],1,For The Soul,TECH HOUSE,5305,92,https://www.beatport.com/track/for-the-soul/22...,+1
69,70,26,True,"MILKY, MALL GRAB","[MILKY, MALL GRAB]",2,Just The Way You Are,HOUSE,5302,82,https://www.beatport.com/track/just-the-way-yo...,+26
70,71,0,False,SOSA (UK),[SOSA (UK)],1,Be Without You,TECH HOUSE,5289,83,https://www.beatport.com/track/be-without-you/...,0
71,72,1,True,"KASKADE, CID, ANABEL ENGLUND","[KASKADE, CID, ANABEL ENGLUND]",3,Vision Blurred,TECH HOUSE,5181,69,https://www.beatport.com/track/vision-blurred/...,+1
72,73,0,False,QULIANO,[QULIANO],1,NYC,TECH HOUSE,5149,88,https://www.beatport.com/track/nyc/20029418,0
73,74,0,False,"CHRIS LAKE, SKRILLEX, ANITA B QUEEN","[CHRIS LAKE, SKRILLEX, ANITA B QUEEN]",3,LA NOCHE,BASS HOUSE,5116,86,https://www.beatport.com/track/la-noche/21893118,0
74,75,0,False,"SHIMZA, KASANGO, AR/CO","[SHIMZA, KASANGO, AR/CO]",3,Fire Fire,AFRO HOUSE,5103,115,https://www.beatport.com/track/fire-fire/20614372,0
75,76,0,False,MAU P,[MAU P],1,TESLA,TECH HOUSE,5070,82,https://www.beatport.com/track/tesla/20630687,0
76,77,0,False,JORDAN PEAK,[JORDAN PEAK],1,Front 2 Back,HOUSE,5069,76,https://www.beatport.com/track/front-2-back/20...,0
77,78,0,False,MAX STYLER,[MAX STYLER],1,I Know You Want To,TECH HOUSE,4993,99,https://www.beatport.com/track/i-know-you-want...,0
78,79,1,True,"RIORDAN, A+","[RIORDAN, A+]",2,Party Out,TECH HOUSE,4875,61,https://www.beatport.com/track/party-out/22910099,+1
79,80,98,True,"RIORDAN, SILVA BUMPA","[RIORDAN, SILVA BUMPA]",2,Lifting,UK GARAGE / BASSLINE,4823,61,https://www.beatport.com/track/lifting/24441099,+98
80,81,1,True,"WESTEND, SIDEPIECE","[WESTEND, SIDEPIECE]",2,Take Your Places,BASS HOUSE,4822,72,https://www.beatport.com/track/take-your-place...,+1
81,82,1,True,"JOSH BAKER, PAIGE CAVELL, SILVA BUMPA","[JOSH BAKER, PAIGE CAVELL, SILVA BUMPA]",3,Feel This Way,HOUSE,4745,63,https://www.beatport.com/track/feel-this-way/2...,+1
82,83,3,True,BRITNEY SPEARS,[BRITNEY SPEARS],1,I Wanna Go (John Summit Extended Remix),DANCE / POP,4656,83,https://www.beatport.com/track/i-wanna-go/2223...,+3
83,84,0,False,"PROSPA, RAHH","[PROSPA, RAHH]",2,This Rhythm (feat. RAHH),HOUSE,4646,97,https://www.beatport.com/track/this-rhythm-fea...,0
84,85,2,True,"DELERIUM, SARAH MCLACHLAN, JOHN SUMMIT","[DELERIUM, SARAH MCLACHLAN, JOHN SUMMIT]",3,Silence feat. Sarah McLachlan,DANCE / POP,4646,79,https://www.beatport.com/track/silence-feat-sa...,+2
85,86,2,True,CALVIN HARRIS,[CALVIN HARRIS],1,I'm Not Alone,UK GARAGE / BASSLINE,4634,94,https://www.beatport.com/track/im-not-alone/21...,+2
86,87,2,True,"TIGA, MEDUZA","[TIGA, MEDUZA]",2,You Gonna Want Me (I Know),MELODIC HOUSE & TECHNO,4594,81,https://www.beatport.com/track/you-gonna-want-...,+2
87,88,2,True,HATIRAS,[HATIRAS],1,Hypnotized,TECH HOUSE,4571,88,https://www.beatport.com/track/hypnotized/2062...,+2
88,89,2,True,BRADEAZY,[BRADEAZY],1,Up Down,BASS HOUSE,4538,112,https://www.beatport.com/track/up-down/21302857,+2
89,90,3,True,"MELOKO, KONVEX (FR), GARLA","[MELOKO, KONVEX (FR), GARLA]",3,If U Ever,MELODIC HOUSE & TECHNO,4441,76,https://www.beatport.com/track/if-u-ever/20778427,+3
90,91,3,True,LAYTON GIORDANI,[LAYTON GIORDANI],1,Hold It Down (DARE),TECH HOUSE,4437,63,https://www.beatport.com/track/hold-it-down-da...,+3
91,92,5,True,"MAX DEAN, LUKE DEAN","[MAX DEAN, LUKE DEAN]",2,Gets Like That,HOUSE,4402,61,https://www.beatport.com/track/gets-like-that/...,+5
92,93,0,False,"JOHN SUMMIT, CLOVES","[JOHN SUMMIT, CLOVES]",2,Focus feat. CLOVES (Alok Extended Remix),MELODIC HOUSE & TECHNO,4384,66,https://www.beatport.com/track/focus-feat-clov...,0
93,94,0,False,"&ME, RAMPA, ADAM PORT, KEINEMUSIK, CHUALA","[&ME, RAMPA, ADAM PORT, KEINEMUSIK, CHUALA]",5,Say What (feat. Chuala),AFRO HOUSE,4294,86,https://www.beatport.com/track/say-what-feat-c...,0
94,95,5,True,"SMOKEY BUBBLIN' B, GUY BURNS, JAMES POOLE","[SMOKEY BUBBLIN' B, GUY BURNS, JAMES POOLE]",3,Temptation,HOUSE,4284,55,https://www.beatport.com/track/temptation/2245...,+5
95,96,0,False,"LOW STEPPA, CAPRI (UK)","[LOW STEPPA, CAPRI (UK)]",2,Got The Funk,HOUSE,4277,75,https://www.beatport.com/track/got-the-funk/20...,0
96,97,4,True,KI/KI,[KI/KI],1,What's a Girl to Do in '25 (Extended),TRANCE (MAIN FLOOR),4273,95,https://www.beatport.com/track/whats-a-girl-to...,+4
97,98,4,True,"MC DT, SILVA BUMPA","[MC DT, SILVA BUMPA]",2,Doin' It feat. MC DT,UK GARAGE / BASSLINE,4272,114,https://www.beatport.com/track/doin-it-feat-mc...,+4
98,99,4,True,"BOYS NOIZE, &ME, RAMPA, ADAM PORT, KEINEMUSIK,...","[BOYS NOIZE, &ME, RAMPA, ADAM PORT, KEINEMUSIK...",6,Crazy For It (feat. Vinson),MELODIC HOUSE & TECHNO,4236,68,https://www.beatport.com/track/crazy-for-it-fe...,+4
99,100,4,True,DUMITRESCU,[DUMITRESCU],1,Sitting In The Sun (Walking In The Rain),DANCE / POP,4234,59,https://www.beatport.com/track/sitting-in-the-...,+4

In [16]:
df["movement_str"] = df["movement"].apply(lambda x: f"+{x}" if x > 0 else str(x))

df[["rank", "movement", "movement_str", "movement_direction", "artist_raw", "title", "genre"]].head(20)

,rank,movement,movement_str,movement_direction,artist_raw,title,genre
0,1,0,0,flat,"JONAS BLUE, MALIVE",Edge of Desire,HOUSE
1,2,0,0,flat,"TINASHE, DISCO LINES",No Broke Boys,DANCE / POP
2,3,0,0,flat,MAU P,Like I Like It,TECH HOUSE
3,4,0,0,flat,"HUGEL, SOLTO (FR)",Jamaican (Bam Bam),AFRO HOUSE
4,5,3,+3,up,JAMBACK,Positive,MINIMAL / DEEP TECH
5,6,0,0,flat,TOMAN,Verano En NY,TECH HOUSE
6,7,0,0,flat,"CID, TAYLR RENEE",Fancy $hit,TECH HOUSE
7,8,0,0,flat,PROSPA,Don't Stop,TECH HOUSE
8,9,0,0,flat,"PROSPA, KOSMO KINT",Love Songs (feat. Kosmo Kint),HOUSE
9,10,1,+1,up,"DA HOOL, CASSIAN, YOTTO",Love Parade,MELODIC HOUSE & TECHNO
10,11,1,+1,up,SIDEPIECE,Cry For You,DANCE / POP
11,12,9,+9,up,"ULTRA NATE, HUGEL",Free (You Got To Live),AFRO HOUSE
12,13,1,+1,up,BABES ON THE RUN,Power,FUNKY HOUSE
13,14,1,+1,up,"CHRIS LAKE, THE CHEMICAL BROTHERS",Galvanize,DANCE / POP
14,15,1,+1,up,CHRIS LORENZO,Appetite,TECH HOUSE
15,16,2,+2,up,"MAX DEAN, LUKE DEAN, LOCKY (UK)",Can't Decide,DEEP HOUSE
16,17,3,+3,up,"CALVIN HARRIS, CLEMENTINE DOUGLAS",Blessings,DANCE / POP
17,18,4,+4,up,"AUDIO BULLYS, CHRIS LORENZO, MAX STYLER",London's On Fire,TECH HOUSE
18,19,5,+5,up,"KATE LINN, PROVI, FANTOMEL",Dame Un Grrr (Provi Remix),AFRO HOUSE
19,20,5,+5,up,FALLON (IE),Diet Coke,TECH HOUSE

In [17]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

df

,rank,movement,movement_direction,artist_raw,artists,title,genre,points,days,beatport_link,movement_str
0,1,0,flat,"JONAS BLUE, MALIVE","[JONAS BLUE, MALIVE]",Edge of Desire,HOUSE,21094,285,https://www.beatport.com/track/edge-of-desire/...,0
1,2,0,flat,"TINASHE, DISCO LINES","[TINASHE, DISCO LINES]",No Broke Boys,DANCE / POP,17922,258,https://www.beatport.com/track/no-broke-boys/2...,0
2,3,0,flat,MAU P,[MAU P],Like I Like It,TECH HOUSE,16951,251,https://www.beatport.com/track/like-i-like-it/...,0
3,4,0,flat,"HUGEL, SOLTO (FR)","[HUGEL, SOLTO (FR)]",Jamaican (Bam Bam),AFRO HOUSE,16248,173,https://www.beatport.com/track/jamaican-bam-ba...,0
4,5,3,up,JAMBACK,[JAMBACK],Positive,MINIMAL / DEEP TECH,15176,173,https://www.beatport.com/track/positive/22236272,+3
5,6,0,flat,TOMAN,[TOMAN],Verano En NY,TECH HOUSE,13549,228,https://www.beatport.com/track/verano-en-ny/20...,0
6,7,0,flat,"CID, TAYLR RENEE","[CID, TAYLR RENEE]",Fancy $hit,TECH HOUSE,13304,170,https://www.beatport.com/track/fancy-hit/21309496,0
7,8,0,flat,PROSPA,[PROSPA],Don't Stop,TECH HOUSE,12579,237,https://www.beatport.com/track/dont-stop/20311844,0
8,9,0,flat,"PROSPA, KOSMO KINT","[PROSPA, KOSMO KINT]",Love Songs (feat. Kosmo Kint),HOUSE,12178,174,https://www.beatport.com/track/love-songs-feat...,0
9,10,1,up,"DA HOOL, CASSIAN, YOTTO","[DA HOOL, CASSIAN, YOTTO]",Love Parade,MELODIC HOUSE & TECHNO,11337,154,https://www.beatport.com/track/love-parade/217...,+1
10,11,1,up,SIDEPIECE,[SIDEPIECE],Cry For You,DANCE / POP,11170,156,https://www.beatport.com/track/cry-for-you/215...,+1
11,12,9,up,"ULTRA NATE, HUGEL","[ULTRA NATE, HUGEL]",Free (You Got To Live),AFRO HOUSE,10713,151,https://www.beatport.com/track/free-you-got-to...,+9
12,13,1,up,BABES ON THE RUN,[BABES ON THE RUN],Power,FUNKY HOUSE,10626,224,https://www.beatport.com/track/power/20692753,+1
13,14,1,up,"CHRIS LAKE, THE CHEMICAL BROTHERS","[CHRIS LAKE, THE CHEMICAL BROTHERS]",Galvanize,DANCE / POP,10594,146,https://www.beatport.com/track/galvanize/21200241,+1
14,15,1,up,CHRIS LORENZO,[CHRIS LORENZO],Appetite,TECH HOUSE,10406,162,https://www.beatport.com/track/appetite/20450483,+1
15,16,2,up,"MAX DEAN, LUKE DEAN, LOCKY (UK)","[MAX DEAN, LUKE DEAN, LOCKY (UK)]",Can't Decide,DEEP HOUSE,9683,189,https://www.beatport.com/track/cant-decide/205...,+2
16,17,3,up,"CALVIN HARRIS, CLEMENTINE DOUGLAS","[CALVIN HARRIS, CLEMENTINE DOUGLAS]",Blessings,DANCE / POP,9601,132,https://www.beatport.com/track/blessings/20462394,+3
17,18,4,up,"AUDIO BULLYS, CHRIS LORENZO, MAX STYLER","[AUDIO BULLYS, CHRIS LORENZO, MAX STYLER]",London's On Fire,TECH HOUSE,9283,154,https://www.beatport.com/track/londons-on-fire...,+4
18,19,5,up,"KATE LINN, PROVI, FANTOMEL","[KATE LINN, PROVI, FANTOMEL]",Dame Un Grrr (Provi Remix),AFRO HOUSE,9148,146,https://www.beatport.com/track/dame-un-grrr-pr...,+5
19,20,5,up,FALLON (IE),[FALLON (IE)],Diet Coke,TECH HOUSE,8996,117,https://www.beatport.com/track/diet-coke/22095452,+5
20,21,22,up,BRUNELLO,[BRUNELLO],Ghost Dance,INDIE DANCE,8836,121,https://www.beatport.com/track/ghost-dance/231...,+22
21,22,5,up,"VANCO, AYA.SYSTEM","[VANCO, AYA.SYSTEM]",Ma Tnsani (Yalla Habibi) (feat. AYA.SYSTEM),AFRO HOUSE,8792,149,https://www.beatport.com/track/ma-tnsani-yalla...,+5
22,23,0,flat,"CHRIS LAKE, RAGIE BAN","[CHRIS LAKE, RAGIE BAN]",Toxic,TECH HOUSE,8520,138,https://www.beatport.com/track/toxic/20291674,0
23,24,8,up,SUPERNOVA,[SUPERNOVA],Velvet Avenue,HOUSE,8452,134,https://www.beatport.com/track/velvet-avenue/2...,+8
24,25,3,up,VINTER (BR),[VINTER (BR)],Space Pump,HOUSE,8297,124,https://www.beatport.com/track/space-pump/2102...,+3
25,26,3,up,"EMPIRE OF THE SUN, BLOND:ISH","[EMPIRE OF THE SUN, BLOND:ISH]",Walking On A Dream,DANCE / POP,8211,133,https://www.beatport.com/track/walking-on-a-dr...,+3
26,27,0,flat,"JOCELYN BROWN, LUKE ALESSI, CHLOé CAILLET","[JOCELYN BROWN, LUKE ALESSI, CHLOé CAILLET]",The One,HOUSE,8097,125,https://www.beatport.com/track/the-one/20307568,0
27,28,0,flat,MAU P,[MAU P],The Less I Know The Better,TECH HOUSE,7838,139,https://www.beatport.com/track/the-less-i-know...,0
28,29,2,up,FEZZO,[FEZZO],Kids,DANCE / POP,7786,84,https://www.beatport.com/track/kids/22448219,+2
29,30,3,up,"KURD MAVERICK, HUGEL","[KURD MAVERICK, HUGEL]",PYHU (Put Your Hands Up),AFRO HOUSE,7590,119,https://www.beatport.com/track/pyhu-put-your-h...,+3
30,31,3,up,"SHAKEDOWN, LAYTON GIORDANI, ANYMA (OFC)","[SHAKEDOWN, LAYTON GIORDANI, ANYMA (OFC)]",At Night (Anyma x Layton Giordani Extended Remix),MELODIC HOUSE & TECHNO,7542,123,https://www.beatport.com/track/at-night/20661162,+3
31,32,3,up,JULIAN FIJMA,[JULIAN FIJMA],Get Stupid,MINIMAL / DEEP TECH,7539,124,https://www.beatport.com/track/get-stupid/2088...,+3
32,33,3,up,"BOBBY SHMURDA, SIDEPIECE","[BOBBY SHMURDA, SIDEPIECE]",Cash Out,TECH HOUSE,7506,134,https://www.beatport.com/track/cash-out/20566956,+3
33,34,0,flat,RÜFÜS DU SOL,[RÜFÜS DU SOL],In the Moment (Adriatique Extended Remix),MELODIC HOUSE & TECHNO,7498,155,https://www.beatport.com/track/in-the-moment/2...,0
34,35,2,up,"MODJO, SPARROW & BARBOSSA, KOSHI, DAYMAAN, SPA...","[MODJO, SPARROW & BARBOSSA, KOSHI, DAYMAAN, SP...",Lady (Hear Me Tonight) - Remix,AFRO HOUSE,7469,120,https://www.beatport.com/track/lady-hear-me-to...,+2
35,36,42,up,MAU P,[MAU P],neck,TECH HOUSE,7340,82,https://www.beatport.com/track/neck/23308330,+42
36,37,48,up,TRACE (UZ),[TRACE (UZ)],Good Time,HOUSE,7337,81,https://www.beatport.com/track/good-time/23443670,+48
37,38,0,flat,BISCITS,[BISCITS],Crush,TECH HOUSE,7210,107,https://www.beatport.com/track/crush/20362602,0
38,39,0,flat,"NATE DOGG, KOLTER","[NATE DOGG, KOLTER]",Liquor Store,HOUSE,6986,92,https://www.beatport.com/track/liquor-store/20...,0
39,40,0,flat,"CAMELPHAT, ELDERBROOK, ARTBAT","[CAMELPHAT, ELDERBROOK, ARTBAT]",Cola,TECH HOUSE,6957,98,https://www.beatport.com/track/cola/20790162,0
40,41,0,flat,BONAFIQUE,[BONAFIQUE],Monologue,INDIE DANCE,6953,154,https://www.beatport.com/track/monologue/20962298,0
41,42,6,up,"NICK CURLY, JOëLLA JACKSON","[NICK CURLY, JOëLLA JACKSON]",Attention,DEEP HOUSE,6937,138,https://www.beatport.com/track/attention/22480525,+6
42,43,36,up,ESSE (US),[ESSE (US)],Make My Day,TECH HOUSE,6857,84,https://www.beatport.com/track/make-my-day/234...,+36
43,44,0,flat,"VINTAGE CULTURE, GABSS","[VINTAGE CULTURE, GABSS]",Lost,MELODIC HOUSE & TECHNO,6804,76,https://www.beatport.com/track/lost/22738898,0
44,45,0,flat,"EMANUELE ESPOSITO, GIANNI ROMANO, HELEN TESFAZ...","[EMANUELE ESPOSITO, GIANNI ROMANO, HELEN TESFA...",It's Not Right,AFRO HOUSE,6753,126,https://www.beatport.com/track/its-not-right/2...,0
45,46,0,flat,SAMM (BE),[SAMM (BE)],Body Language,HOUSE,6636,90,https://www.beatport.com/track/body-language/2...,0
46,47,34,up,JOSHWA,[JOSHWA],Out of My Mind,TECH HOUSE,6466,82,https://www.beatport.com/track/out-of-my-mind/...,+34
47,48,51,up,"REINIER ZONNEVELD, GORDO","[REINIER ZONNEVELD, GORDO]",Loco Loco,DANCE / POP,6448,75,https://www.beatport.com/track/loco-loco/23904036,+51
48,49,0,flat,"ADAM PORT, STRYV, MALACHIII","[ADAM PORT, STRYV, MALACHIII]",Positions,AFRO HOUSE,6424,91,https://www.beatport.com/track/positions/20674436,0
49,50,0,flat,SCRIPT,[SCRIPT],WTF,TECH HOUSE,6324,106,https://www.beatport.com/track/wtf/20796447,0
50,51,0,flat,"MK, CHRYSTAL","[MK, CHRYSTAL]",Dior,HOUSE,6297,95,https://www.beatport.com/track/dior/20528357,0
51,52,0,flat,MESTO,[MESTO],Caramelle,MAINSTAGE,6272,85,https://www.beatport.com/track/caramelle/22741059,0
52,53,0,flat,"MARSHALL JEFFERSON, MAESIC, SALOMé DAS","[MARSHALL JEFFERSON, MAESIC, SALOMé DAS]",Life Is Simple (Move Your Body),AFRO HOUSE,6219,100,https://www.beatport.com/track/life-is-simple-...,0
53,54,0,flat,"MR. BELT & WEZOL, RUZE","[MR. BELT & WEZOL, RUZE]",Ain't Nobody,HOUSE,6183,92,https://www.beatport.com/track/aint-nobody/213...,0
54,55,0,flat,DISCIP,[DISCIP],Pull Up,TECH HOUSE,6110,80,https://www.beatport.com/track/pull-up/22866908,0
55,56,0,flat,L.P. RHYTHM,[L.P. RHYTHM],Versatile,HOUSE,6022,89,https://www.beatport.com/track/versatile/20719741,0
56,57,0,flat,"TIESTO, ODD MOB, GOODBOYS","[TIESTO, ODD MOB, GOODBOYS]",Won't Be Possible,DANCE / POP,5971,91,https://www.beatport.com/track/wont-be-possibl...,0
57,58,0,flat,"THREE DRIVES, THREE DRIVES ON A VINYL, MAX STYLER","[THREE DRIVES, THREE DRIVES ON A VINYL, MAX ST...",Greece 2000,TRANCE (MAIN FLOOR),5772,80,https://www.beatport.com/track/greece-2000/230...,0
58,59,1,up,ALAIA & GALLO,[ALAIA & GALLO],Lipstick,TECH HOUSE,5696,114,https://www.beatport.com/track/lipstick/20572171,+1
59,60,1,up,"ODD MOB, OMNOM, HYPERBEAM","[ODD MOB, OMNOM, HYPERBEAM]",Coming Up (It's Dare),DANCE / POP,5682,84,https://www.beatport.com/track/coming-up-its-d...,+1
60,61,1,up,MPH,[MPH],Raw,UK GARAGE / BASSLINE,5645,130,https://www.beatport.com/track/raw/20533994,+1
61,62,1,up,"CALVIN HARRIS, D.O.D","[CALVIN HARRIS, D.O.D]",Sweet Nothing,DANCE / POP,5635,86,https://www.beatport.com/track/sweet-nothing/2...,+1
62,63,1,up,"HECTOR COUTO, ALEJANDRO PAZ","[HECTOR COUTO, ALEJANDRO PAZ]",El House,HOUSE,5486,89,https://www.beatport.com/track/el-house/20431852,+1
63,64,1,up,EMANUEL SATIE,[EMANUEL SATIE],Give It All,HOUSE,5473,85,https://www.beatport.com/track/give-it-all/223...,+1
64,65,2,up,"ODD MOB, OMNOM, HYPERBEAM","[ODD MOB, OMNOM, HYPERBEAM]",System,TECH HOUSE,5387,78,https://www.beatport.com/track/system/21251156,+2
65,66,2,up,"MOBY, BLOND:ISH, KIKO FRANCO","[MOBY, BLOND:ISH, KIKO FRANCO]",Natural Blues,HOUSE,5359,73,https://www.beatport.com/track/natural-blues/2...,+2
66,67,155,up,"ANOTR, 54 ULTRA","[ANOTR, 54 ULTRA]",Talk To You,HOUSE,5345,54,https://www.beatport.com/track/talk-to-you/245...,+155
67,68,1,up,"SONNY FODERA, D.O.D, POPPY BASKCOMB","[SONNY FODERA, D.O.D, POPPY BASKCOMB]",Think About Us,DANCE / POP,5322,119,https://www.beatport.com/track/think-about-us/...,+1
68,69,1,up,TINI GESSLER,[TINI GESSLER],For The Soul,TECH HOUSE,5305,92,https://www.beatport.com/track/for-the-soul/22...,+1
69,70,26,up,"MILKY, MALL GRAB","[MILKY, MALL GRAB]",Just The Way You Are,HOUSE,5302,82,https://www.beatport.com/track/just-the-way-yo...,+26
70,71,0,flat,SOSA (UK),[SOSA (UK)],Be Without You,TECH HOUSE,5289,83,https://www.beatport.com/track/be-without-you/...,0
71,72,1,up,"KASKADE, CID, ANABEL ENGLUND","[KASKADE, CID, ANABEL ENGLUND]",Vision Blurred,TECH HOUSE,5181,69,https://www.beatport.com/track/vision-blurred/...,+1
72,73,0,flat,QULIANO,[QULIANO],NYC,TECH HOUSE,5149,88,https://www.beatport.com/track/nyc/20029418,0
73,74,0,flat,"CHRIS LAKE, SKRILLEX, ANITA B QUEEN","[CHRIS LAKE, SKRILLEX, ANITA B QUEEN]",LA NOCHE,BASS HOUSE,5116,86,https://www.beatport.com/track/la-noche/21893118,0
74,75,0,flat,"SHIMZA, KASANGO, AR/CO","[SHIMZA, KASANGO, AR/CO]",Fire Fire,AFRO HOUSE,5103,115,https://www.beatport.com/track/fire-fire/20614372,0
75,76,0,flat,MAU P,[MAU P],TESLA,TECH HOUSE,5070,82,https://www.beatport.com/track/tesla/20630687,0
76,77,0,flat,JORDAN PEAK,[JORDAN PEAK],Front 2 Back,HOUSE,5069,76,https://www.beatport.com/track/front-2-back/20...,0
77,78,0,flat,MAX STYLER,[MAX STYLER],I Know You Want To,TECH HOUSE,4993,99,https://www.beatport.com/track/i-know-you-want...,0
78,79,1,up,"RIORDAN, A+","[RIORDAN, A+]",Party Out,TECH HOUSE,4875,61,https://www.beatport.com/track/party-out/22910099,+1
79,80,98,up,"RIORDAN, SILVA BUMPA","[RIORDAN, SILVA BUMPA]",Lifting,UK GARAGE / BASSLINE,4823,61,https://www.beatport.com/track/lifting/24441099,+98
80,81,1,up,"WESTEND, SIDEPIECE","[WESTEND, SIDEPIECE]",Take Your Places,BASS HOUSE,4822,72,https://www.beatport.com/track/take-your-place...,+1
81,82,1,up,"JOSH BAKER, PAIGE CAVELL, SILVA BUMPA","[JOSH BAKER, PAIGE CAVELL, SILVA BUMPA]",Feel This Way,HOUSE,4745,63,https://www.beatport.com/track/feel-this-way/2...,+1
82,83,3,up,BRITNEY SPEARS,[BRITNEY SPEARS],I Wanna Go (John Summit Extended Remix),DANCE / POP,4656,83,https://www.beatport.com/track/i-wanna-go/2223...,+3
83,84,0,flat,"PROSPA, RAHH","[PROSPA, RAHH]",This Rhythm (feat. RAHH),HOUSE,4646,97,https://www.beatport.com/track/this-rhythm-fea...,0
84,85,2,up,"DELERIUM, SARAH MCLACHLAN, JOHN SUMMIT","[DELERIUM, SARAH MCLACHLAN, JOHN SUMMIT]",Silence feat. Sarah McLachlan,DANCE / POP,4646,79,https://www.beatport.com/track/silence-feat-sa...,+2
85,86,2,up,CALVIN HARRIS,[CALVIN HARRIS],I'm Not Alone,UK GARAGE / BASSLINE,4634,94,https://www.beatport.com/track/im-not-alone/21...,+2
86,87,2,up,"TIGA, MEDUZA","[TIGA, MEDUZA]",You Gonna Want Me (I Know),MELODIC HOUSE & TECHNO,4594,81,https://www.beatport.com/track/you-gonna-want-...,+2
87,88,2,up,HATIRAS,[HATIRAS],Hypnotized,TECH HOUSE,4571,88,https://www.beatport.com/track/hypnotized/2062...,+2
88,89,2,up,BRADEAZY,[BRADEAZY],Up Down,BASS HOUSE,4538,112,https://www.beatport.com/track/up-down/21302857,+2
89,90,3,up,"MELOKO, KONVEX (FR), GARLA","[MELOKO, KONVEX (FR), GARLA]",If U Ever,MELODIC HOUSE & TECHNO,4441,76,https://www.beatport.com/track/if-u-ever/20778427,+3
90,91,3,up,LAYTON GIORDANI,[LAYTON GIORDANI],Hold It Down (DARE),TECH HOUSE,4437,63,https://www.beatport.com/track/hold-it-down-da...,+3
91,92,5,up,"MAX DEAN, LUKE DEAN","[MAX DEAN, LUKE DEAN]",Gets Like That,HOUSE,4402,61,https://www.beatport.com/track/gets-like-that/...,+5
92,93,0,flat,"JOHN SUMMIT, CLOVES","[JOHN SUMMIT, CLOVES]",Focus feat. CLOVES (Alok Extended Remix),MELODIC HOUSE & TECHNO,4384,66,https://www.beatport.com/track/focus-feat-clov...,0
93,94,0,flat,"&ME, RAMPA, ADAM PORT, KEINEMUSIK, CHUALA","[&ME, RAMPA, ADAM PORT, KEINEMUSIK, CHUALA]",Say What (feat. Chuala),AFRO HOUSE,4294,86,https://www.beatport.com/track/say-what-feat-c...,0
94,95,5,up,"SMOKEY BUBBLIN' B, GUY BURNS, JAMES POOLE","[SMOKEY BUBBLIN' B, GUY BURNS, JAMES POOLE]",Temptation,HOUSE,4284,55,https://www.beatport.com/track/temptation/2245...,+5
95,96,0,flat,"LOW STEPPA, CAPRI (UK)","[LOW STEPPA, CAPRI (UK)]",Got The Funk,HOUSE,4277,75,https://www.beatport.com/track/got-the-funk/20...,0
96,97,4,up,KI/KI,[KI/KI],What's a Girl to Do in '25 (Extended),TRANCE (MAIN FLOOR),4273,95,https://www.beatport.com/track/whats-a-girl-to...,+4
97,98,4,up,"MC DT, SILVA BUMPA","[MC DT, SILVA BUMPA]",Doin' It feat. MC DT,UK GARAGE / BASSLINE,4272,114,https://www.beatport.com/track/doin-it-feat-mc...,+4
98,99,4,up,"BOYS NOIZE, &ME, RAMPA, ADAM PORT, KEINEMUSIK,...","[BOYS NOIZE, &ME, RAMPA, ADAM PORT, KEINEMUSIK...",Crazy For It (feat. Vinson),MELODIC HOUSE & TECHNO,4236,68,https://www.beatport.com/track/crazy-for-it-fe...,+4
99,100,4,up,DUMITRESCU,[DUMITRESCU],Sitting In The Sun (Walking In The Rain),DANCE / POP,4234,59,https://www.beatport.com/track/sitting-in-the-...,+4

In [60]:
print("Total tracks:", len(df))
print("Min rank:", df["rank"].min())
print("Max rank:", df["rank"].max())
print("Unique ranks:", df["rank"].nunique())
print("Duplicate ranks:", df["rank"].duplicated().sum())
print("\nMissing values:")
print(df.isnull().sum())

Total tracks: 100
Min rank: 1
Max rank: 100
Unique ranks: 100
Duplicate ranks: 0

Missing values:
rank             0
rise_amount      0
is_rising        0
artist_raw       0
artists          0
num_artists      0
title            0
genre            0
points           0
days             0
beatport_link    0
rise_str         0
dtype: int64

In [61]:
df.describe()

             rank  rise_amount  num_artists        points        days
count  100.000000   100.000000   100.000000    100.000000  100.000000
mean    50.500000     6.500000     1.920000   7275.000000  112.890000
std     29.011492    20.157712     1.011849   3240.017845   46.734344
min      1.000000     0.000000     1.000000   4234.000000   54.000000
25%     25.750000     0.000000     1.000000   5094.750000   82.000000
50%     50.500000     1.000000     2.000000   6310.500000   95.000000
75%     75.250000     3.000000     3.000000   8232.500000  134.000000
max    100.000000   155.000000     6.000000  21094.000000  285.000000

In [62]:
df["genre"].value_counts().head(30)

genre
TECH HOUSE                28
HOUSE                     22
DANCE / POP               14
AFRO HOUSE                11
MELODIC HOUSE & TECHNO     8
UK GARAGE / BASSLINE       4
BASS HOUSE                 3
MINIMAL / DEEP TECH        2
DEEP HOUSE                 2
INDIE DANCE                2
TRANCE (MAIN FLOOR)        2
FUNKY HOUSE                1
MAINSTAGE                  1
Name: count, dtype: int64

In [63]:
df["rise_amount"].value_counts().sort_index()

rise_amount
0      40
1      17
2      10
3      11
4       5
5       5
6       1
8       1
9       1
22      1
26      1
34      1
36      1
42      1
48      1
51      1
98      1
155     1
Name: count, dtype: int64

In [64]:
df.sort_values("rise_amount", ascending=False)[
    ["rank", "rise_str", "artist_raw", "title", "genre"]
].head(15)

,rank,rise_str,artist_raw,title,genre
66,67,+155,"ANOTR, 54 ULTRA",Talk To You,HOUSE
79,80,+98,"RIORDAN, SILVA BUMPA",Lifting,UK GARAGE / BASSLINE
47,48,+51,"REINIER ZONNEVELD, GORDO",Loco Loco,DANCE / POP
36,37,+48,TRACE (UZ),Good Time,HOUSE
35,36,+42,MAU P,neck,TECH HOUSE
42,43,+36,ESSE (US),Make My Day,TECH HOUSE
46,47,+34,JOSHWA,Out of My Mind,TECH HOUSE
69,70,+26,"MILKY, MALL GRAB",Just The Way You Are,HOUSE
20,21,+22,BRUNELLO,Ghost Dance,INDIE DANCE
11,12,+9,"ULTRA NATE, HUGEL",Free (You Got To Live),AFRO HOUSE
23,24,+8,SUPERNOVA,Velvet Avenue,HOUSE
41,42,+6,"NICK CURLY, JOëLLA JACKSON",Attention,DEEP HOUSE
18,19,+5,"KATE LINN, PROVI, FANTOMEL",Dame Un Grrr (Provi Remix),AFRO HOUSE
94,95,+5,"SMOKEY BUBBLIN' B, GUY BURNS, JAMES POOLE",Temptation,HOUSE
91,92,+5,"MAX DEAN, LUKE DEAN",Gets Like That,HOUSE

In [65]:
df["is_rising"].value_counts()

is_rising
True     60
False    40
Name: count, dtype: int64

In [66]:
df_artists = df.explode("artists").reset_index(drop=True)
df_artists.head(20)

,rank,rise_amount,is_rising,artist_raw,artists,num_artists,title,genre,points,days,beatport_link,rise_str
0,1,0,False,"JONAS BLUE, MALIVE",JONAS BLUE,2,Edge of Desire,HOUSE,21094,285,https://www.beatport.com/track/edge-of-desire/...,0
1,1,0,False,"JONAS BLUE, MALIVE",MALIVE,2,Edge of Desire,HOUSE,21094,285,https://www.beatport.com/track/edge-of-desire/...,0
2,2,0,False,"TINASHE, DISCO LINES",TINASHE,2,No Broke Boys,DANCE / POP,17922,258,https://www.beatport.com/track/no-broke-boys/2...,0
3,2,0,False,"TINASHE, DISCO LINES",DISCO LINES,2,No Broke Boys,DANCE / POP,17922,258,https://www.beatport.com/track/no-broke-boys/2...,0
4,3,0,False,MAU P,MAU P,1,Like I Like It,TECH HOUSE,16951,251,https://www.beatport.com/track/like-i-like-it/...,0
5,4,0,False,"HUGEL, SOLTO (FR)",HUGEL,2,Jamaican (Bam Bam),AFRO HOUSE,16248,173,https://www.beatport.com/track/jamaican-bam-ba...,0
6,4,0,False,"HUGEL, SOLTO (FR)",SOLTO (FR),2,Jamaican (Bam Bam),AFRO HOUSE,16248,173,https://www.beatport.com/track/jamaican-bam-ba...,0
7,5,3,True,JAMBACK,JAMBACK,1,Positive,MINIMAL / DEEP TECH,15176,173,https://www.beatport.com/track/positive/22236272,+3
8,6,0,False,TOMAN,TOMAN,1,Verano En NY,TECH HOUSE,13549,228,https://www.beatport.com/track/verano-en-ny/20...,0
9,7,0,False,"CID, TAYLR RENEE",CID,2,Fancy $hit,TECH HOUSE,13304,170,https://www.beatport.com/track/fancy-hit/21309496,0
10,7,0,False,"CID, TAYLR RENEE",TAYLR RENEE,2,Fancy $hit,TECH HOUSE,13304,170,https://www.beatport.com/track/fancy-hit/21309496,0
11,8,0,False,PROSPA,PROSPA,1,Don't Stop,TECH HOUSE,12579,237,https://www.beatport.com/track/dont-stop/20311844,0
12,9,0,False,"PROSPA, KOSMO KINT",PROSPA,2,Love Songs (feat. Kosmo Kint),HOUSE,12178,174,https://www.beatport.com/track/love-songs-feat...,0
13,9,0,False,"PROSPA, KOSMO KINT",KOSMO KINT,2,Love Songs (feat. Kosmo Kint),HOUSE,12178,174,https://www.beatport.com/track/love-songs-feat...,0
14,10,1,True,"DA HOOL, CASSIAN, YOTTO",DA HOOL,3,Love Parade,MELODIC HOUSE & TECHNO,11337,154,https://www.beatport.com/track/love-parade/217...,+1
15,10,1,True,"DA HOOL, CASSIAN, YOTTO",CASSIAN,3,Love Parade,MELODIC HOUSE & TECHNO,11337,154,https://www.beatport.com/track/love-parade/217...,+1
16,10,1,True,"DA HOOL, CASSIAN, YOTTO",YOTTO,3,Love Parade,MELODIC HOUSE & TECHNO,11337,154,https://www.beatport.com/track/love-parade/217...,+1
17,11,1,True,SIDEPIECE,SIDEPIECE,1,Cry For You,DANCE / POP,11170,156,https://www.beatport.com/track/cry-for-you/215...,+1
18,12,9,True,"ULTRA NATE, HUGEL",ULTRA NATE,2,Free (You Got To Live),AFRO HOUSE,10713,151,https://www.beatport.com/track/free-you-got-to...,+9
19,12,9,True,"ULTRA NATE, HUGEL",HUGEL,2,Free (You Got To Live),AFRO HOUSE,10713,151,https://www.beatport.com/track/free-you-got-to...,+9

In [67]:
artist_counts = df_artists["artists"].value_counts().reset_index()
artist_counts.columns = ["artist", "track_count"]

artist_counts.head(20)

             artist  track_count
0             MAU P            4
1         ADAM PORT            3
2            PROSPA            3
3         SIDEPIECE            3
4     CALVIN HARRIS            3
5           ODD MOB            3
6        MAX STYLER            3
7       SILVA BUMPA            3
8             HUGEL            3
9        CHRIS LAKE            3
10        BLOND:ISH            2
11      JOHN SUMMIT            2
12            D.O.D            2
13              &ME            2
14        HYPERBEAM            2
15          RIORDAN            2
16        LUKE DEAN            2
17  LAYTON GIORDANI            2
18         MAX DEAN            2
19    CHRIS LORENZO            2

In [68]:
artist_summary = (
    df_artists.groupby("artists", as_index=False)
    .agg(
        track_count=("title", "count"),
        avg_points=("points", "mean"),
        avg_days=("days", "mean"),
        rising_tracks=("is_rising", "sum")
    )
    .sort_values(["track_count", "avg_points"], ascending=[False, False])
)

artist_summary.head(20)

             artists  track_count    avg_points    avg_days  rising_tracks
94             MAU P            4   9299.750000  138.500000              1
60             HUGEL            3  11517.000000  147.666667              2
113           PROSPA            3   9801.000000  169.333333              0
29        CHRIS LAKE            3   8076.666667  123.333333              1
129        SIDEPIECE            3   7832.666667  120.666667              3
96        MAX STYLER            3   6682.666667  111.000000              1
24     CALVIN HARRIS            3   6623.333333  104.000000              3
109          ODD MOB            3   5680.000000   84.333333              2
4          ADAM PORT            3   4984.666667   81.666667              1
130      SILVA BUMPA            3   4613.333333   79.333333              3
30     CHRIS LORENZO            2   9844.500000  158.000000              2
33               CID            2   9242.500000  119.500000              1
88         LUKE DEAN            2   7042.500000  125.000000              2
95          MAX DEAN            2   7042.500000  125.000000              2
17         BLOND:ISH            2   6785.000000  103.000000              2
84   LAYTON GIORDANI            2   5989.500000   93.000000              2
61         HYPERBEAM            2   5534.500000   81.000000              2
110            OMNOM            2   5534.500000   81.000000              2
36             D.O.D            2   5478.500000  102.500000              2
120          RIORDAN            2   4849.000000   61.000000              2

In [69]:
df.sort_values("num_artists", ascending=False)[
    ["rank", "num_artists", "artist_raw", "title", "genre"]
].head(15)

,rank,num_artists,artist_raw,title,genre
98,99,6,"BOYS NOIZE, &ME, RAMPA, ADAM PORT, KEINEMUSIK,...",Crazy For It (feat. Vinson),MELODIC HOUSE & TECHNO
93,94,5,"&ME, RAMPA, ADAM PORT, KEINEMUSIK, CHUALA",Say What (feat. Chuala),AFRO HOUSE
34,35,5,"MODJO, SPARROW & BARBOSSA, KOSHI, DAYMAAN, SPA...",Lady (Hear Me Tonight) - Remix,AFRO HOUSE
44,45,4,"EMANUELE ESPOSITO, GIANNI ROMANO, HELEN TESFAZ...",It's Not Right,AFRO HOUSE
74,75,3,"SHIMZA, KASANGO, AR/CO",Fire Fire,AFRO HOUSE
30,31,3,"SHAKEDOWN, LAYTON GIORDANI, ANYMA (OFC)",At Night (Anyma x Layton Giordani Extended Remix),MELODIC HOUSE & TECHNO
65,66,3,"MOBY, BLOND:ISH, KIKO FRANCO",Natural Blues,HOUSE
26,27,3,"JOCELYN BROWN, LUKE ALESSI, CHLOé CAILLET",The One,HOUSE
67,68,3,"SONNY FODERA, D.O.D, POPPY BASKCOMB",Think About Us,DANCE / POP
71,72,3,"KASKADE, CID, ANABEL ENGLUND",Vision Blurred,TECH HOUSE
73,74,3,"CHRIS LAKE, SKRILLEX, ANITA B QUEEN",LA NOCHE,BASS HOUSE
59,60,3,"ODD MOB, OMNOM, HYPERBEAM",Coming Up (It's Dare),DANCE / POP
18,19,3,"KATE LINN, PROVI, FANTOMEL",Dame Un Grrr (Provi Remix),AFRO HOUSE
17,18,3,"AUDIO BULLYS, CHRIS LORENZO, MAX STYLER",London's On Fire,TECH HOUSE
57,58,3,"THREE DRIVES, THREE DRIVES ON A VINYL, MAX STYLER",Greece 2000,TRANCE (MAIN FLOOR)

In [70]:
df["num_artists"].value_counts().sort_index()

num_artists
1    42
2    32
3    22
4     1
5     2
6     1
Name: count, dtype: int64

In [30]:
artist_summary = (
    df_artists.groupby("artists", as_index=False)
    .agg(
        track_count=("title", "count"),
        avg_points=("points", "mean"),
        avg_days=("days", "mean"),
        avg_movement=("movement", "mean")
    )
    .sort_values(["track_count", "avg_points"], ascending=[False, False])
)

artist_summary.head(20)

             artists  track_count    avg_points    avg_days  avg_movement
94             MAU P            4   9299.750000  138.500000     10.500000
60             HUGEL            3  11517.000000  147.666667      4.000000
113           PROSPA            3   9801.000000  169.333333      0.000000
29        CHRIS LAKE            3   8076.666667  123.333333      0.333333
129        SIDEPIECE            3   7832.666667  120.666667      1.666667
96        MAX STYLER            3   6682.666667  111.000000      1.333333
24     CALVIN HARRIS            3   6623.333333  104.000000      2.000000
109          ODD MOB            3   5680.000000   84.333333      1.000000
4          ADAM PORT            3   4984.666667   81.666667      1.333333
130      SILVA BUMPA            3   4613.333333   79.333333     34.333333
30     CHRIS LORENZO            2   9844.500000  158.000000      2.500000
33               CID            2   9242.500000  119.500000      0.500000
88         LUKE DEAN            2   7042.500000  125.000000      3.500000
95          MAX DEAN            2   7042.500000  125.000000      3.500000
17         BLOND:ISH            2   6785.000000  103.000000      2.500000
84   LAYTON GIORDANI            2   5989.500000   93.000000      3.000000
61         HYPERBEAM            2   5534.500000   81.000000      1.500000
110            OMNOM            2   5534.500000   81.000000      1.500000
36             D.O.D            2   5478.500000  102.500000      1.000000
120          RIORDAN            2   4849.000000   61.000000     49.500000

In [71]:
df_export = df.copy()
df_export["artists"] = df_export["artists"].apply(lambda x: " | ".join(x))

df_export.to_csv("../data/processed/all_genres_chart_clean.csv", index=False)
print("Saved ../data/processed/all_genres_chart_clean.csv")

Saved ../data/processed/all_genres_chart_clean.csv